kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: papertrail
  namespace: default
data:
  host: logs.papertrailapp.com
  port: "12345"
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: default
  name: my-config
  creationTimestamp: 2017-02-01T17:15:23Z
data:
  api-key: stuff