#!/bin/bash

set -e

SHA1=$1
APP_ENV=$2
SERVICE_NAME=$3
# Optional - e.g. :ghost:
SLACK_EMOJI=$4

source ./kube-stack/switch-kube-environment $APP_ENV/eu-west-1

./kube-stack/deploy/deploy-docker $SHA1 $APP_ENV $SERVICE_NAME

# Tell everyone what we're doing
./kube-stack/deploy/notify-slack $SERVICE_NAME $APP_ENV $SLACK_EMOJI

YAML_FILE=$(./kube-stack/deploy/get-deploy-yaml $APP_ENV)
echo 'Using $YAML_FILE for deployment'

# Start in US West and roll eastwards, but there is no staging environment in US West.
if [ "${APP_ENV}" != "staging" ]; then
    ./kube-stack/deploy/deploy-to-kube $YAML_FILE $APP_ENV us-west-1 $SERVICE_NAME
fi
./kube-stack/deploy/deploy-to-kube $YAML_FILE $APP_ENV us-east-1 $SERVICE_NAME
./kube-stack/deploy/deploy-to-kube $YAML_FILE $APP_ENV eu-west-1 $SERVICE_NAME
