#!/bin/bash

set -e

if ! type "helm" > /dev/null; then
    echo "It looks like you don't have helm yet... installing it. ⛑"

    OS=$(echo `uname`|tr '[:upper:]' '[:lower:]')

    ARCH=$(uname -m)
    case $ARCH in
        armv5*) ARCH="armv5";;
        armv6*) ARCH="armv6";;
        armv7*) ARCH="armv7";;
        aarch64) ARCH="arm64";;
        x86) ARCH="386";;
        x86_64) ARCH="amd64";;
        i686) ARCH="386";;
        i386) ARCH="386";;
    esac

    curl -O https://storage.googleapis.com/kubernetes-helm/helm-v2.3.0-$OS-$ARCH.tar.gz
    tar zxf helm-v2.3.0-$OS-$ARCH.tar.gz
    sudo mv $OS-$ARCH/helm /usr/local/bin/helm
    sudo chmod 777 /usr/local/bin/helm
fi