#!/bin/bash

set -e

YELLOW='\033[0;93m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

# If the realpath tool isn't installed, you need it
if ! type "realpath" > /dev/null; then

    echo -e "${YELLOW}☁️  Installing realpath${NC}"

    # OS Detection
    if [ "$(uname)" == "Darwin" ]; then
        set -x
        brew install coreutils
        set +x
    else
        set -x
        sudo apt-get -qq install realpath
        set +x
    fi

fi