#!/bin/bash

set -e

GREEN='\033[0;32m'
YELLOW='\033[0;93m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

# This assumes you're running the script from the folder above this one (i.e. ../).
KUBE_ENV=$1

export CLOUDSDK_PYTHON_SITEPACKAGES=1
export GOOGLE_APPLICATION_CREDENTIALS=$(realpath $KUBE_ENV/gce-service-account.json)
export GOOGLE_PROJECT_ID=$(jq -r '.project_id' $GOOGLE_APPLICATION_CREDENTIALS)

echo -e "${CYAN}🔑  Loading GCE service account private key for $KUBE_ENV...${NC}"
gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
CREDENTIALS=$(cat $KUBE_ENV/gce-credentials.txt)
echo -e "${CYAN}⛈  GCE credentials are: $CREDENTIALS ${NC}"

# In GCE land we have to look up a service account for each kube cluster.
# This improves security, as it limits access across regions/environments if we lose a private key.
gcloud container clusters get-credentials $CREDENTIALS
gcloud config set project $GOOGLE_PROJECT_ID
