#!/bin/bash

set -e 

# Run this in your script using `source iam/set-aws-credentials`
KUBE_ENV=$1

# This assumes you're running the script from the folder above this one (i.e. ../).
source ./iam/set-aws-access-keys
cp -f ./$KUBE_ENV/config ~/.kube/config

cp -f ./$KUBE_ENV/kube_aws_rsa ~/.ssh/ 2>/dev/null || :
cp -f ./$KUBE_ENV/kube_aws_rsa.pub ~/.ssh/ 2>/dev/null || :